chore(deps): Bump library/ruby from 3.4.5-slim to 3.4.6-slim in the d… (#465)
chore(deps): Bump library/ruby from 3.4.5-slim to 3.4.6-slim in the docker group

Signed-off-by: Steve Hipwell <steve.hipwell@gmail.com>

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -52,7 +52,7 @@ jobs:
 
   build:
     name: Build
-    uses: action-stars/build-workflows/.github/workflows/build-oci-image.yaml@523aa243519dfa15b6efb00b95d057d15fb1dbb7 # v0.9.0
+    uses: action-stars/build-workflows/.github/workflows/build-oci-image.yaml@b069d468d8f4618d7203d342afc4ecf82667201f # v0.10.0
     needs: setup
     if: github.event_name == 'workflow_dispatch' || needs.setup.outputs.changed == 'true'
     permissions:
@@ -86,12 +86,43 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
+        with:
+          fetch-depth: 0
+
+      - name: Lookup snapshot
+        id: snapshot
+        env:
+          GH_TOKEN: ${{ github.token }}
+        run: |
+          set -euo pipefail
+
+          base_sha="${{ github.event.pull_request.base.sha }}"
+          head_sha="${{ github.event.pull_request.head.sha }}"
+
+          counter="0"
+          while ((counter < 10)); do
+            if [[ -z "$(gh api --header "Accept: application/vnd.github+json" --header "X-GitHub-Api-Version: 2022-11-28" --include "/repos/${{ github.repository }}/dependency-graph/compare/${base_sha}...${head_sha}" | grep -E 'X-Github-Dependency-Graph-Snapshot-Warnings:\s*[a-zA-Z0-9]+' || true)" ]]; then
+              echo "::notice::Snapshot found on SHA ${base_sha}"
+              {
+                echo "base_sha=${base_sha}"
+                echo "head_sha=${head_sha}"
+              } >> "${GITHUB_OUTPUT}"
+              exit 0
+            fi
+
+            base_sha="$(git rev-parse "${base_sha}~1")"
+            counter=$((counter+1))
+          done
+
+          echo "::error::Snapshot not found"
+          exit 1
 
       - name: Dependency Review
         uses: actions/dependency-review-action@595b5aeba73380359d98a5e087f648dbb0edce1b # v4.7.3
         with:
+          base-ref: ${{ steps.snapshot.outputs.base_sha }}
+          head-ref: ${{ steps.snapshot.outputs.head_sha }}
           fail-on-severity: high
-          retry-on-snapshot-warnings: true
           comment-summary-in-pr: always
 
   check:
