chore: Add dependency review workflow (#415)
Signed-off-by: Steve Hipwell <steve.hipwell@gmail.com>

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -72,9 +72,31 @@ jobs:
       push_sarif: true
       push_image: true
 
+  review:
+    name: Dependency Review
+    needs: build
+    if: github.event_name == 'pull_request'
+    runs-on: ubuntu-latest
+    permissions:
+      contents: read
+      pull-requests: write
+    defaults:
+      run:
+        shell: bash
+    steps:
+      - name: Checkout
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+
+      - name: Dependency Review
+        uses: actions/dependency-review-action@3b139cfc5fae8b618d3eae3675e383bb1769c019 # v4.5.0
+        with:
+          comment-summary-in-pr: always
+
   check:
     name: Check
-    needs: build
+    needs:
+      - build
+      - review
     if: always()
     runs-on: ubuntu-latest
     defaults:
@@ -85,7 +107,11 @@ jobs:
         run: |
           set -euo pipefail
 
-          if [[ "${{ needs.build.result }}" == "failure" ]] || [[ "${{ needs.build.result }}" == "cancelled" ]]; then
-            echo "::error::Workflow failed!"
-            exit 1
-          fi
+          results="${{ join(needs.*.result, ' ') }}"
+
+          for result in ${results}; do
+            if [[ "$result" == "failure" ]] || [[ "$result" == "cancelled" ]]; then
+              echo "::error::Workflow failed!"
+              exit 1
+            fi
+          done
